### ISSUE TITLE
BeatUpServer graph URLs not visible under master server list

### ISSUE THREAD

**Issue by rcelyte** [roydejong/bssb.app#14]
BeatUpServer lobbies created through a graph URL (i.e. https://bssb.app/game/roAOE, https://bssb.app/game/1V01v) do not list the associated master server at https://bssb.app/master-servers.

**Comment by roydejong** [comment]
Thanks! Should now be fixed (https://github.com/roydejong/bssb.app/commit/e4e634998a0d39f6920ea6b7fb40ef037c08fd27) as soon as a BeatUpServer announcement comes in

**Comment by rcelyte** [comment]
Now it's there, but the status check seemingly isn't working.
![status](https://user-images.githubusercontent.com/25163630/236581475-f1139051-33b0-4cf1-98c9-cf0a7c2a69fe.png)

**Comment by roydejong** [comment]
Looks like it's good now after some time has passed.

Not definitively sure why, but it looks like the status took a bit to update. I've pushed an update that prioritizes recently seen master servers for the background job that handles this.
