### ISSUE TITLE
Add 'trending' option for map list

### ISSUE THREAD

**Issue by jabberjabberjabber** [roydejong/bssb.app#7]
I think that 'trending' would be a lot more useful than 'top 100' in the map lists.  Top 100 get skewed towards older maps and does not show what people like to play currently.  

The ranking could be using the following criteria:

- Age of the map / first appearance of the map on multiplayer
- Times map completed with more than 1 player using map (this could prevent someone trying to get a map moved higher by playing it by themselves and then giving up over and over)
- Number of times completed in arbitrary time period vs previous arbitrary time period as a function of growth

Thanks for taking the time to evaluate this idea.

**Comment by roydejong** [comment]
Thanks, solid feedback.

I've been wanting to do something like this for a while, and these are some really good points. Appreciate it!

**Comment by roydejong** [comment]
This will be tweaked a bit more and I want to add playlist generation, but the basic concept is up:
https://bssb.app/stats/top/trending-levels

**Comment by roydejong** [comment]
Playlist feature is now live!

This beautiful playlist cover art I made really brings it home I think

![BSSBTop100TrendingLevels](https://user-images.githubusercontent.com/6772638/201364681-f5b68895-41ec-4d57-abeb-caa165e64cfd.png)

**Comment by jabberjabberjabber** [comment]
Haha... beautiful

**Comment by jabberjabberjabber** [comment]
Thanks!

**Comment by roydejong** [comment]
I've been tweaking the algorithm a bit further today.

The biggest challenge is trying to nerf challenge maps that seemingly get a disproportional amount of plays on every day and in every week. "RUSH E" and "Infant Annihilator" should not be trending nonstop...

I've been increasing the weight of levels that are performing better relative to their daily average and decreasing the weight of older levels, and I think we're starting to see some more interesting results now.

**Comment by roydejong** [comment]
Mostly I just want more people to play levels so I can have more data :)

**Comment by jabberjabberjabber** [comment]
Idea: what if we took the datapoints and graph them (plays = y, hours = x), then for each time period find the slope of the line (deltaY / deltaX) and use that as a weighting, so like 

`rank = map values from lowest 0 to highest 100 ( [previous rank*slope] * (1/totaltimeoncharts + magicnumber))'

sorry, math is not my forte and I am terrible at coding, but it is a general idea?  If it is awful I won't be surprised so don't hesitate to say so.

**Comment by jabberjabberjabber** [comment]
> Mostly I just want more people to play levels so I can have more data :)

I will do my best to add some more data.  If you see a beatupserver with someone on it, feel free to jump in.

**Comment by jabberjabberjabber** [comment]
I think it is working pretty well.  I am not sure about the protocols of github, should I close it since I opened it, or do I leave it alone?

**Comment by roydejong** [comment]
I think I'm happy for the moment as well, so I think it's fine to close this issue out. I'll go ahead and do that.

This algorithm probably could still do with some more tweaking, but that will happen over time.

Bigger fish to fry in a sense: how to get more people to enjoy and play multiplayer so I have more data points :)
